name: time
channels:
  - conda-forge
dependencies:
- python=3.9
- jupyter
- jupyterlab
- notebook
- ipykernel
- ipywidgets
- jupytext
- pip
- RISE
- altair
- matplotlib
- numpy
- pandas
- scikit-learn
- seaborn
- scipy
- statsmodels
- prophet
- plotly>=4.0
- scikit-lego

